/*-
 * WSDL stubs for:  tvDataDelivery.wsdl
 *   Generated by:  awk
 *           Date:  Fri Jan 12 11:21:07 2007
 *        Emitter:  Objective-C
 */

#ifndef __tvDataDelivery__
#define __tvDataDelivery__

#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import "WSGeneratedObj.h"
#import "PreferenceKeys.h"

extern NSString *kWebServicesSDPath;

@interface tvDataDelivery : WSGeneratedObj

// We just override some SOAP processing messages to perform authentication
@end;

/*-
 *   Web Service:  xtvdWebService
 * Documentation:  <not documented>
 */
/*-
 *   Method Name:  acknowledge
 * Documentation:  <no documentation>
 */

@interface acknowledge : tvDataDelivery

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* acknowledge */


/*-
 *   Method Name:  download
 * Documentation:  <no documentation>
 */

@interface download : tvDataDelivery

// update the parameter list for the invocation.
- (void) setParameters:(CFTypeRef /* Complex type urn:TMSWebServices|dateTime */) in_startTime in_endTime:(CFTypeRef /* Complex type urn:TMSWebServices|dateTime */) in_endTime;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* download */


/*-
 * Web Service:  xtvdWebService
 */
@interface xtvdWebService : NSObject 

+ (id) acknowledge;
+ (id) download:(CFTypeRef /* Complex type urn:TMSWebServices|dateTime */) in_startTime in_endTime:(CFTypeRef /* Complex type urn:TMSWebServices|dateTime */) in_endTime;

@end;

@interface xtvdDownloadThread : NSObject

+ (void) performDownload:(id)downloadInfo;

@end;

#endif /* __tvDataDelivery__ */
/*-
 * End of WSDL document at tvDataDelivery.wsdl
 */
